name: drag_engine
description: A cross-platform drag and drop engine for Flutter applications, optimized for mobile devices.
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.24.0

flutter:
  # This package is a Flutter package with platform-specific implementations
